"""Backend orchestration for the FSI multi-agent demo (DEPLOYED hosted agents).

Each scenario is served by ONE Foundry HOSTED agent in the target project. For a
run the BFF invokes the agent's Responses endpoint in **background mode** (POST with
``background=true`` returns immediately, then we poll ``GET .../responses/{id}`` until the
status is ``completed``). Background mode is required because long code_interpreter runs
exceed the Foundry gateway's non-streaming connection window (plain ``stream=false`` gets a
``RemoteProtocolError`` disconnect).

The hosted agent's ArtifactEgressMiddleware uploads any generated .xlsx/.pptx to the private
``artifacts`` blob container and appends a ``<<<ARTIFACT name=<f> blob=<container>/<path>>>>``
sentinel to the response text. This orchestrator parses those sentinels, downloads the blobs
privately (managed identity, no SAS), registers them for ``/api/artifacts/{id}`` download,
and strips the sentinel lines from the text shown to the user.
"""
import asyncio
import json
import re
import tempfile
import time
import uuid
import zipfile
from functools import lru_cache
from pathlib import Path
from xml.sax.saxutils import escape
from typing import AsyncIterator, Dict

import httpx
from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient

from .config import (
    AGENT_NAMES,
    ARTIFACTS_CONTAINER,
    DATA_CONTEXT,
    DISCLAIMER,
    SCENARIOS,
    STORAGE_BLOB_ENDPOINT,
    agent_responses_base,
)
from .telemetry import get_tracer

_tracer = get_tracer()
_AI_SCOPE = "https://ai.azure.com/.default"

# id -> {"path": str, "filename": str, "media_type": str}
ARTIFACTS: Dict[str, dict] = {}
_ARTIFACT_DIR = Path(tempfile.gettempdir()) / "fsi_artifacts"
_ARTIFACT_DIR.mkdir(exist_ok=True)

_SENTINEL_RE = re.compile(r"^<<<ARTIFACT name=(?P<name>[^>]+?) blob=(?P<blob>[^>]*)>>>\s*$", re.M)

_MEDIA = {
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".csv": "text/csv",
    ".pdf": "application/pdf",
    ".png": "image/png",
}

_POLL_INTERVAL_S = 5
_POLL_TIMEOUT_S = 900

_FALLBACK_NAMES = {
    "equity-research": "equity_research_agent_summary.xlsx",
    "ib-pitch": "ib_pitch_agent_summary.xlsx",
    "pe-lbo": "pe_lbo_agent_summary.xlsx",
}


def _sse(event: dict) -> str:
    return f"data: {json.dumps(event)}\n\n"


@lru_cache(maxsize=1)
def _credential() -> DefaultAzureCredential:
    return DefaultAzureCredential()


@lru_cache(maxsize=1)
def _blob_service() -> BlobServiceClient:
    return BlobServiceClient(account_url=STORAGE_BLOB_ENDPOINT, credential=_credential())


def _bearer() -> str:
    return _credential().get_token(_AI_SCOPE).token


def _register_artifact(fname: str, data: bytes) -> dict:
    art_id = uuid.uuid4().hex
    dest = _ARTIFACT_DIR / f"{art_id}_{fname}"
    dest.write_bytes(data)
    media = _MEDIA.get(Path(fname).suffix.lower(), "application/octet-stream")
    ARTIFACTS[art_id] = {"path": str(dest), "filename": fname, "media_type": media}
    return {"id": art_id, "filename": fname, "url": f"/api/artifacts/{art_id}"}


def _cell(row: int, value: str) -> str:
    safe = escape(value, {'"': '&quot;'})
    return f'<c r="A{row}" t="inlineStr"><is><t>{safe}</t></is></c>'


def _build_summary_workbook(scenario_key: str, text: str) -> bytes:
    """Create a tiny valid XLSX fallback when hosted artifact egress misses."""
    title = SCENARIOS.get(scenario_key, {}).get("title", scenario_key)
    lines = [
        "Fallback artifact generated by the API because the hosted agent completed "
        "without publishing a Blob artifact sentinel.",
        f"Scenario: {title}",
        "",
        "Agent narrative:",
        *(text or "(No narrative returned.)").splitlines(),
    ]
    rows = "\n".join(f'<row r="{idx}">{_cell(idx, line[:32000])}</row>' for idx, line in enumerate(lines, 1))
    sheet = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        '<cols><col min="1" max="1" width="120" customWidth="1"/></cols>'
        f"<sheetData>{rows}</sheetData>"
        "</worksheet>"
    )
    parts = {
        "[Content_Types].xml": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            '<Default Extension="xml" ContentType="application/xml"/>'
            '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
            '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
            '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
            "</Types>"
        ),
        "_rels/.rels": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
            "</Relationships>"
        ),
        "xl/workbook.xml": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
            'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
            '<sheets><sheet name="Agent Summary" sheetId="1" r:id="rId1"/></sheets>'
            "</workbook>"
        ),
        "xl/_rels/workbook.xml.rels": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
            '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
            "</Relationships>"
        ),
        "xl/styles.xml": (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            '<fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts>'
            '<fills count="1"><fill><patternFill patternType="none"/></fill></fills>'
            '<borders count="1"><border/></borders>'
            '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
            '<cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs>'
            "</styleSheet>"
        ),
        "xl/worksheets/sheet1.xml": sheet,
    }
    dest = tempfile.SpooledTemporaryFile()
    with zipfile.ZipFile(dest, "w", compression=zipfile.ZIP_DEFLATED) as z:
        for name, content in parts.items():
            z.writestr(name, content)
    dest.seek(0)
    return dest.read()


def _response_text(payload: dict) -> str:
    """Concatenate the assistant text from an OpenAI Responses payload."""
    chunks = []
    for item in payload.get("output", []) or []:
        if item.get("type") not in (None, "message"):
            continue
        for part in item.get("content", []) or []:
            if part.get("type") in ("output_text", "text"):
                chunks.append(part.get("text", ""))
    if not chunks and payload.get("output_text"):
        chunks.append(payload["output_text"])
    return "\n".join(chunks)


def _download_blob_sync(blobref: str) -> bytes:
    container, _, blobpath = blobref.partition("/")
    client = _blob_service().get_blob_client(container or ARTIFACTS_CONTAINER, blobpath)
    return client.download_blob().readall()


def _harvest_from_text_sync(text: str) -> tuple[str, list[dict]]:
    """Parse ARTIFACT sentinels, download each blob, return (clean_text, artifacts)."""
    artifacts: list[dict] = []
    for m in _SENTINEL_RE.finditer(text):
        name, blobref = m.group("name").strip(), m.group("blob").strip()
        if not blobref:
            artifacts.append({"id": None, "filename": name, "error": "no blob path"})
            continue
        try:
            data = _download_blob_sync(blobref)
            artifacts.append(_register_artifact(name, data))
        except Exception as e:  # noqa: BLE001
            artifacts.append({"id": None, "filename": name, "error": str(e)[:200]})
    clean = _SENTINEL_RE.sub("", text).strip()
    return clean, artifacts


def _artifact_retry_input(scenario_key: str, message: str, previous_text: str) -> str:
    return (
        _build_input(scenario_key, message)
        + "\n\nCORRECTIVE ARTIFACT TURN:\n"
        "The prior answer did not publish a downloadable portal artifact. It may have "
        "only mentioned a sandbox:/mnt/data link. That is not sufficient for this "
        "application. You MUST call the code_interpreter tool in this turn and create "
        "the requested Office file with Python under /mnt/data. If a loaded skill says "
        "to use Bash or a local shell, adapt that instruction to code_interpreter "
        "Python instead. Do not answer with only text, markdown tables, or a sandbox "
        "link. Save the file and then provide a concise summary.\n\n"
        f"Previous text-only answer for context:\n{previous_text[:2000]}"
    )


def _build_input(scenario_key: str, message: str) -> str:
    return (
        f"{DISCLAIMER}\n\n"
        f"USER REQUEST:\n{message}\n\n"
        f"SYNTHETIC DATASET (authoritative source for NovaGrid Technologies + peers; "
        f"code_interpreter has no internet, so use this data):\n{DATA_CONTEXT}\n\n"
        "SEC EDGAR guidance: if the user provides a real public ticker, keep filing "
        "retrieval compact. Use SEC company info and recent filing metadata first; "
        "request only a small set of named XBRL metrics when needed. Do not fetch full "
        "filing sections, full filing content, or broad financial statements unless "
        "the user explicitly asks for them, because those long retrievals can time out.\n\n"
        "Now do the work: (1) load the relevant skill(s); (2) you MUST call the "
        "code_interpreter tool to build the real workbook/deck file(s) with openpyxl / "
        "python-pptx and save them under /mnt/data — do NOT reproduce the model or slides "
        "as text tables in your reply; the saved file IS the deliverable. If a loaded "
        "skill says to use Bash or a local shell, adapt that step to code_interpreter "
        "Python because no Bash tool is available in this hosted runtime. Do not claim a "
        "sandbox:/mnt/data download link unless code_interpreter actually ran and saved "
        "the file. (3) Then give a "
        "short summary with the headline figures only."
    )


def _is_transient_timeout(error_text: str) -> bool:
    lowered = error_text.lower()
    return (
        "408" in lowered
        or "timeout" in lowered
        or "operation was timeout" in lowered
        or "429" in lowered
        or "rate_limit" in lowered
        or "rate limit" in lowered
    )


def _submit_background_sync(base: str, input_text: str) -> dict:
    with httpx.Client(timeout=120) as c:
        r = c.post(
            f"{base}?api-version=v1",
            headers={"Authorization": f"Bearer {_bearer()}"},
            json={"input": input_text, "stream": False, "store": True, "background": True},
        )
        r.raise_for_status()
        return r.json()


def _poll_once_sync(base: str, response_id: str) -> dict:
    with httpx.Client(timeout=60) as c:
        r = c.get(
            f"{base}/{response_id}?api-version=v1",
            headers={"Authorization": f"Bearer {_bearer()}"},
        )
        r.raise_for_status()
        return r.json()


async def run_scenario(scenario_key: str, message: str) -> AsyncIterator[str]:
    """Async generator yielding SSE strings for a full deployed-agent run."""
    scenario = SCENARIOS.get(scenario_key)
    if not scenario:
        yield _sse({"type": "error", "message": f"Unknown scenario '{scenario_key}'"})
        return

    agent_name = AGENT_NAMES.get(scenario_key, f"fsi-{scenario_key}")
    base = agent_responses_base(scenario_key)

    scenario_span = _tracer.start_span("scenario.run")
    scenario_span.set_attribute("fsi.scenario", scenario_key)
    scenario_span.set_attribute("fsi.toolbox", scenario["toolbox"])
    scenario_span.set_attribute("fsi.agent", agent_name)
    yield _sse({"type": "status", "stage": "start", "scenario": scenario_key,
                "title": scenario["title"], "toolbox": scenario["toolbox"]})
    yield _sse({"type": "agent_start", "agent": agent_name, "role": "scenario",
                "label": scenario["title"]})

    n_artifacts = 0
    clean_text = ""
    had_error = False
    with _tracer.start_as_current_span("agent.turn") as span:
        span.set_attribute("fsi.agent", agent_name)
        span.set_attribute("fsi.role", "scenario")
        try:
            primary_input = _build_input(scenario_key, message)
            payload = {}
            for attempt in range(2):
                try:
                    yield _sse({"type": "status", "stage": "submitting",
                                "scenario": scenario_key})
                    submit = await asyncio.to_thread(
                        _submit_background_sync, base, primary_input
                    )
                    rid = submit.get("id")
                    status = submit.get("status")
                    if not rid:
                        raise RuntimeError(f"no response id from submit: {json.dumps(submit)[:300]}")

                    t0 = time.time()
                    payload = submit
                    while status in ("queued", "in_progress"):
                        await asyncio.sleep(_POLL_INTERVAL_S)
                        elapsed = int(time.time() - t0)
                        yield _sse({"type": "status", "stage": "working",
                                    "scenario": scenario_key, "elapsed_s": elapsed})
                        if elapsed > _POLL_TIMEOUT_S:
                            raise TimeoutError(f"agent run exceeded {_POLL_TIMEOUT_S}s")
                        payload = await asyncio.to_thread(_poll_once_sync, base, rid)
                        status = payload.get("status")

                    if status != "completed":
                        err = payload.get("error") or {"message": f"status={status}"}
                        raise RuntimeError(f"agent run {status}: {json.dumps(err)[:300]}")
                    break
                except Exception as exc:  # noqa: BLE001
                    if attempt == 0 and _is_transient_timeout(str(exc)):
                        yield _sse({"type": "status", "stage": "retrying",
                                    "scenario": scenario_key})
                        await asyncio.sleep(20)
                        continue
                    raise

            raw_text = _response_text(payload)
            clean_text, artifacts = await asyncio.to_thread(_harvest_from_text_sync, raw_text)

            if not any(art.get("id") for art in artifacts):
                yield _sse({"type": "status", "stage": "ensuring_artifact",
                            "scenario": scenario_key})
                try:
                    submit = await asyncio.to_thread(
                        _submit_background_sync,
                        base,
                        _artifact_retry_input(scenario_key, message, clean_text or raw_text),
                    )
                    rid = submit.get("id")
                    status = submit.get("status")
                    if not rid:
                        raise RuntimeError(f"no response id from artifact retry: {json.dumps(submit)[:300]}")

                    t0 = time.time()
                    payload = submit
                    while status in ("queued", "in_progress"):
                        await asyncio.sleep(_POLL_INTERVAL_S)
                        elapsed = int(time.time() - t0)
                        yield _sse({"type": "status", "stage": "working",
                                    "scenario": scenario_key, "elapsed_s": elapsed})
                        if elapsed > _POLL_TIMEOUT_S:
                            raise TimeoutError(f"artifact retry exceeded {_POLL_TIMEOUT_S}s")
                        payload = await asyncio.to_thread(_poll_once_sync, base, rid)
                        status = payload.get("status")

                    if status != "completed":
                        err = payload.get("error") or {"message": f"status={status}"}
                        raise RuntimeError(f"artifact retry {status}: {json.dumps(err)[:300]}")

                    retry_text = _response_text(payload)
                    retry_clean, retry_artifacts = await asyncio.to_thread(
                        _harvest_from_text_sync, retry_text
                    )
                    if any(art.get("id") for art in retry_artifacts):
                        clean_text, artifacts = retry_clean, retry_artifacts
                    else:
                        clean_text = retry_clean or clean_text
                except Exception as exc:  # noqa: BLE001
                    span.set_attribute("fsi.artifact_retry_error", str(exc)[:300])

            if not any(art.get("id") for art in artifacts):
                artifacts = [
                    _register_artifact(
                        _FALLBACK_NAMES.get(scenario_key, "agent_summary.xlsx"),
                        _build_summary_workbook(scenario_key, clean_text),
                    )
                ]

            # Deliver the (sentinel-stripped) narrative as a single delta.
            if clean_text:
                yield _sse({"type": "delta", "agent": agent_name, "text": clean_text})

            for art in artifacts:
                if art.get("id"):
                    n_artifacts += 1
                yield _sse({"type": "artifact", "agent": agent_name, **art})
        except Exception as e:  # noqa: BLE001
            had_error = True
            span.set_attribute("fsi.error", str(e)[:300])
            yield _sse({"type": "error", "agent": agent_name, "message": str(e)[:300]})
        span.set_attribute("fsi.artifacts", n_artifacts)
        span.set_attribute("fsi.chars", len(clean_text))
        span.set_attribute("fsi.ok", not had_error)

    yield _sse({"type": "agent_end", "agent": agent_name})
    scenario_span.end()
    yield _sse({"type": "done"})
