"""Generic end-to-end validator for the deployed FSI demo API.

Runs each scenario against the deployed BFF, reads the SSE stream, downloads the
produced artifact, and asserts it is a real OOXML (PK zip) file that is not the API's
last-resort fallback summary artifact. No resource names are hardcoded: the API base
URL comes from --api-base or the API_BASE_URL env var (set by deploy.ps1 from the
infra API_URL output).

Usage:
    python scripts/validate.py --api-base https://<api-fqdn>
    python scripts/validate.py pe-lbo            # single scenario
    python scripts/validate.py --api-base https://<api-fqdn> --portal-origin https://<portal-fqdn> --preflight-only
Exit code is non-zero if any scenario fails, so it doubles as a CI gate.
"""
import argparse
import io
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import zipfile

# scenario -> expected artifact extension
EXPECTED_EXT = {
    "equity-research": ".xlsx",
    "ib-pitch": ".pptx",
    "pe-lbo": ".xlsx",
}

_FALLBACK_NAME_RE = re.compile(r"agent_summary\.(xlsx|pptx)$", re.IGNORECASE)
_FALLBACK_MARKERS = (
    b"Fallback artifact generated by the API",
    b"Fallback deck generated by the API",
    b"without publishing a Blob artifact sentinel",
)


def _api_base(cli_value: str | None) -> str:
    base = (cli_value or os.environ.get("API_BASE_URL", "")).strip().rstrip("/")
    if not base:
        sys.exit(
            "ERROR: API base URL not provided. Pass --api-base or set API_BASE_URL "
            "(e.g. to the API_URL infra output)."
        )
    return base


def run_scenario(base: str, scenario: str, timeout: int = 1800):
    body = json.dumps({"scenario": scenario}).encode()
    req = urllib.request.Request(
        base + "/api/run", data=body, headers={"Content-Type": "application/json"}
    )
    artifacts, errors = [], []
    t0 = time.time()
    with urllib.request.urlopen(req, timeout=timeout) as r:
        for raw in r:
            line = raw.decode("utf-8").strip()
            if not line.startswith("data:"):
                continue
            ev = json.loads(line[5:].strip())
            t = ev.get("type")
            if t == "artifact" and ev.get("id"):
                artifacts.append(ev)
            elif t == "error":
                errors.append(ev.get("message", ""))
    return artifacts, errors, int(time.time() - t0)


def portal_origin(value: str) -> str:
    parsed = urllib.parse.urlsplit(value)
    if (parsed.scheme not in {"http", "https"} or not parsed.hostname or parsed.username
            or parsed.password or parsed.path not in {"", "/"} or parsed.query or parsed.fragment):
        raise argparse.ArgumentTypeError("Portal origin must be an HTTP(S) origin without credentials, path or query.")
    return value.rstrip("/")


def validate_cors(base: str, origin: str) -> bool:
    """Check the real ingress response, without capabilities, writes or model calls."""
    passed = True
    for method, path, headers in (
        ("GET", "/api/health", ()),
        ("POST", "/api/run", ("content-type", "x-webiq-key")),
    ):
        request_headers = {"Origin": origin, "Access-Control-Request-Method": method}
        if headers:
            request_headers["Access-Control-Request-Headers"] = ", ".join(headers)
        req = urllib.request.Request(base + path, method="OPTIONS", headers=request_headers)
        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                allowed_origin = response.headers.get("Access-Control-Allow-Origin", "")
                allowed_methods = {item.strip() for item in
                                   response.headers.get("Access-Control-Allow-Methods", "").split(",")}
                allowed_headers = {item.strip().lower() for item in
                                   response.headers.get("Access-Control-Allow-Headers", "").split(",")}
                valid = (200 <= response.status < 300 and allowed_origin in {origin, "*"}
                         and (method in allowed_methods or "*" in allowed_methods)
                         and (not headers or "*" in allowed_headers or set(headers) <= allowed_headers))
        except (urllib.error.URLError, TimeoutError):
            print(f"[FAIL] browser {method} {path}: CORS preflight could not be read.")
            passed = False
            continue
        if valid:
            print(f"[PASS] browser {method} {path}: ingress permits the portal origin, method and request headers.")
        else:
            print(f"[FAIL] browser {method} {path}: ingress CORS does not permit the portal origin, method or request headers.")
            passed = False
    return passed


def is_ooxml(data: bytes) -> bool:
    # Every .xlsx/.pptx is a zip; zip local file headers start with 'PK\x03\x04'.
    return data[:4] == b"PK\x03\x04"


def is_fallback_filename(name: str) -> bool:
    return bool(_FALLBACK_NAME_RE.search(name or ""))


def is_fallback_ooxml(data: bytes) -> bool:
    try:
        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            for member in zf.namelist():
                if not member.endswith(".xml"):
                    continue
                blob = zf.read(member)
                if any(marker in blob for marker in _FALLBACK_MARKERS):
                    return True
    except zipfile.BadZipFile:
        return False
    return False


def validate(base: str, scenario: str) -> bool:
    ext = EXPECTED_EXT[scenario]
    try:
        artifacts, errors, secs = run_scenario(base, scenario)
    except Exception as e:  # noqa: BLE001
        print(f"[FAIL] {scenario}: request error: {str(e)[:200]}")
        return False

    if errors:
        print(f"[FAIL] {scenario} ({secs}s): errors={errors}")
        return False
    candidates = [a for a in artifacts if a.get("filename", "").lower().endswith(ext)]
    if not candidates:
        print(f"[FAIL] {scenario} ({secs}s): no {ext} artifact; got {[a.get('filename') for a in artifacts]}")
        return False
    match = next((a for a in candidates if not is_fallback_filename(a.get("filename", ""))), candidates[0])

    url = match["url"] if match["url"].startswith("http") else base + match["url"]
    try:
        data = urllib.request.urlopen(url, timeout=120).read()
    except Exception as e:  # noqa: BLE001
        print(f"[FAIL] {scenario}: artifact download error: {str(e)[:200]}")
        return False

    if not is_ooxml(data):
        print(f"[FAIL] {scenario}: '{match['filename']}' is not valid OOXML (no PK zip signature)")
        return False

    if is_fallback_filename(match["filename"]) or is_fallback_ooxml(data):
        print(
            f"[FAIL] {scenario} ({secs}s): '{match['filename']}' is the API fallback summary artifact, "
            "not the real generated deliverable"
        )
        return False

    print(f"[PASS] {scenario} ({secs}s): {match['filename']} ({len(data)} bytes, valid OOXML)")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("scenarios", nargs="*", help="scenarios to run (default: all)")
    ap.add_argument("--api-base", default=None, help="API base URL (or set API_BASE_URL)")
    ap.add_argument("--portal-origin", type=portal_origin, help="Check ingress CORS for this portal origin before scenarios")
    ap.add_argument("--preflight-only", action="store_true", help="Only check CORS; no sessions, writes or model calls")
    args = ap.parse_args()

    if args.preflight_only and (not args.portal_origin or args.scenarios):
        ap.error("--preflight-only requires --portal-origin and no scenarios")
    base = _api_base(args.api_base)
    if args.portal_origin and not validate_cors(base, args.portal_origin):
        sys.exit(1)
    if args.preflight_only:
        sys.exit(0)
    targets = args.scenarios or list(EXPECTED_EXT.keys())
    results = {s: validate(base, s) for s in targets if s in EXPECTED_EXT}
    passed = sum(results.values())
    print(f"\n=== {passed}/{len(results)} scenarios passed ===")
    sys.exit(0 if passed == len(results) and results else 1)


if __name__ == "__main__":
    main()
